drop table if exists friendship;
drop table if exists likes;
drop table if exists film_genre;
drop table if exists genres;
drop table if exists users;
drop table if exists films;
drop table if exists mpa_rating;


CREATE TABLE IF NOT EXISTS mpa_rating
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(16) NOT NULL
);

CREATE TABLE IF NOT EXISTS users
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email     VARCHAR(320) UNIQUE NOT NULL,
    login     VARCHAR(320)        NOT NULL,
    name      VARCHAR(320)        NOT NULL,
    birthdate DATE
);

CREATE TABLE IF NOT EXISTS films
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR      NOT NULL,
    description  VARCHAR(200) NOT NULL,
    release_date DATE,
    duration     SMALLINT,
    mpa_rating   BIGINT REFERENCES mpa_rating (id)
);

CREATE TABLE IF NOT EXISTS genres
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS film_genre
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id  BIGINT NOT NULL REFERENCES films (id) ON DELETE CASCADE,
    genre_id BIGINT NOT NULL REFERENCES genres (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS likes
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (id),
    film_id BIGINT NOT NULL REFERENCES films (id),
    UNIQUE (user_id, film_id)
);

CREATE TABLE IF NOT EXISTS friendship
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id_from BIGINT NOT NULL REFERENCES users (id),
    user_id_to   BIGINT NOT NULL REFERENCES users (id),
    approved     BOOLEAN DEFAULT FALSE,
    UNIQUE (user_id_from, user_id_to)
);

